### ISSUE TITLE
"A" record should not be required for an address to be valid

### ISSUE THREAD

**Issue by ledermann** [heycarsten/email-veracity#1]
See this example:

```
EmailVeracity::Address.new('info@koelnerbank.de').valid?
# => false

EmailVeracity::Address.new('info@koelnerbank.de').domain.exchange_servers.present?
# => true
```

The domain "koelnerbank.de" has no A record (stupid, indeed), but an MX record. IMHO the address should be valid.

Background: 

> When an e-mail message is sent through the Internet, the sending mail transfer agent queries the Domain Name System for MX records of each recipient's domain name. This query returns a list of host names of mail exchange servers accepting incoming mail for that domain and their preferences. The sending agent then attempts to establish an SMTP connection to one of these servers, starting with the one with the smallest preference number, delivering the message to the first server with which a connection can be made. If no MX records were present, the server falls back to A, that is to say, it makes a request for the A record of the same domain.

http://en.wikipedia.org/wiki/MX_record

**Comment by heycarsten** [comment]
Totally correct, I will fix this behaviour.

**Comment by heycarsten** [comment]
This should work properly now.

```
 heycarsten:~ carsten$ irb
 irb(main):001:0> require 'email_veracity'
 => true
 irb(main):002:0> EmailVeracity::Address.new('info@koelnerbank.de').valid?
 => true
```

**Comment by ledermann** [comment]
Yeah, works fine now, thank you!
