### ISSUE TITLE
Disabling MX / A domain checks

### ISSUE THREAD

**Issue by dennmart** [heycarsten/email-veracity#2]
I recently replaced the old 'validates_email_veracity_of' Active Record plugin on a rather-old Rails app with this gem. Now my tests aren't passing properly. Sometimes a test that does validations for the email address will randomly fail, and I discovered it's due to constant domain checking for valid MX or A records.

Is there a configuration option to prevent these checks from happening (for example, do no domain checking while in the test environment)? I was looking at the code (particularly the Config module) and tried changing different options there, but nothing seemed to work. If there's no configuration option for this, there probably should be one. If there is one already, it should be documented.

**Comment by heycarsten** [comment]
A valid issue, I'll add an option to skip the domain checking. Thanks for bringing this up.

**Comment by owain68** [comment]
I would like the same feature since demonstrating an environment in an "offline" mode with a client of my development laptop when there is no internet connectivity.

**Comment by heycarsten** [comment]
Okay, you can now disable domain lookups for validation by setting `Config[:skip_lookup] = true`

**Comment by owain68** [comment]
Thanks a lot.  Having trouble pulling down the updated version from the gem repository http://gems.github.com/  or should I be installing it some other way?

**Comment by dennmart** [comment]
@heycarsten: Thanks for the new config option!

@owain68: These changes were pushed to Gemcutter (http://gemcutter.org/gems/email_veracity). Gemcutter has essentially replaced gem building on GitHub (more info: http://github.com/blog/515-gem-building-is-defunct), so you should add http://gemcutter.org to your gem sources (`gem sources -a http://gemcutter.org`) and then install / upgrade the updated gem.

**Comment by owain68** [comment]
@denmart:  All sorted now.  Also made the underscore mistake!

**Comment by bhellman1** [comment]
Where do you set the Config[:skip_lookup] = true ?

**Comment by owain68** [comment]
@bhellman1
I just created an initializer file:  

<pre><code>#config/initializers.offline.rb 
EmailVeracity::Config[:skip_lookup] = Conf.offline</code></pre>


This picks this up from a config file but you could also just put in the value.
