### ISSUE TITLE
Where can you set skip_lookup => true?

### ISSUE THREAD

**Issue by bhellman1** [heycarsten/email-veracity#3]
In my controller I have: 

class PermissionsController < ApplicationController'

  require 'email_veracity'

......
email_address = EmailVeracity::Address.new(email)

if email_address.valid?

.......

Where can you actually set the option of skip_loop => true?

**Comment by owain68** [comment]
<pre>#config/initializers/offline.rb
EmailVeracity::Config[:skip_lookup] = Conf.offline</pre>

I use AppConfig plugin to pick it up from config.local.yml for the disconnected laptop, and set to false in the main config file for tidiness.  You could test connectivity on startup in the initializer and set accordingly.  Or just put <pre>true</pre> in the offline.rb

**Comment by heycarsten** [comment]
Thanks @owain68 for taking care of that one!
